### ISSUE TITLE
keepassxc-proxy does not close when chromium closes

### ISSUE THREAD

**Issue by Isles487** [varjolintu/keepassxc-proxy#5]
Keepassxc-proxy is working fine with both firefox and chromium portable edition on windows 10, except for the proxy exe does not close after chromium closes. It closes after firefox closes.

Specs:

Windows 10
Chromium Version 64.0.3259.0 (Official Build) (64-bit)
KeepassXC-browser 0.3.9
keepassxc-proxy compiled on 11/5/2017

**Comment by varjolintu** [comment]
Strange behaviour. Will be fixed when I find the reason for this.

**Comment by varjolintu** [comment]
Also, it seems keepassxc-browser crashes if Chrome and proxy is active and you close KeePassXC. I already solved this issue with Firefox but for some reason Chrome handles the Native Messaging very differently on Windows.

**Comment by varjolintu** [comment]
I still haven't resolved this. Haven't found the reason for this even with hours of debugging and modifying the code.

**Comment by mrloyal1410** [comment]
When I disable browser integration option, this issue is resolved.

**Comment by varjolintu** [comment]
@mrloyal1410 Well.. but then the extension won't work at all so I wouldn't count it as a solution.
